stages:
  - build

build-pwa:
  stage: build
  image: node:16.9.0
  script:
        - npm install -g @angular/cli
        - npm uninstall -g ionic
        - npm install -g @ionic/cli
        - npm install
        - CI='' ionic build --prod
    artifacts:
        paths:
            - public
    only:
        - develop
